### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by waterloo3122** [LinhNC/Hackintosh-13900K-Z690-AORUS-ELITE-DDR5-RX-6600XT#1]
what is the relationship with this project ？
https://github.com/rursache/Hackintosh-13900k-Z690-AORUS-ELITE-AX-DDR5-AMD-6900XT.git

**Comment by LinhNC** [comment]
Yes,  it's base on this repo, you can see this author under Thanks/Credits
